version: "3.9"
services:
  salt:
    container_name: salt
    hostname: salt
    image: docker.io/saltstack/salt
    ports:
      - "8000:8000"
      - "4505-4506:4505-4506"
    environment:
      - SALT_SHARED_SECRET=mysecretpassword
    volumes:
      # Mount master configuration drop-in dir:
      - ./salt/etc/salt/master.d:/etc/salt/master.d
      
      # Mount dir where salt master stores its own keys and accepted minion keys
      - ./salt/etc/salt/pki/:/etc/salt/pki/
      
      # Mount salt fire root:
      - ./salt/srv/:/srv/

  
